<?php


 function autoload_96d2f8e914b6a5f32a1e79c3b6aeba4d($class)
{
    $classes = array(
        'Zuora\ZuoraService' => __DIR__ .'/ZuoraService.php',
        'Zuora\zObject' => __DIR__ .'/zObject.php',
        'Zuora\AccountingCode' => __DIR__ .'/AccountingCode.php',
        'Zuora\AccountingPeriod' => __DIR__ .'/AccountingPeriod.php',
        'Zuora\Account' => __DIR__ .'/Account.php',
        'Zuora\InvoiceAdjustment' => __DIR__ .'/InvoiceAdjustment.php',
        'Zuora\InvoiceItemAdjustment' => __DIR__ .'/InvoiceItemAdjustment.php',
        'Zuora\Amendment' => __DIR__ .'/Amendment.php',
        'Zuora\BillRun' => __DIR__ .'/BillRun.php',
        'Zuora\Contact' => __DIR__ .'/Contact.php',
        'Zuora\Invoice' => __DIR__ .'/Invoice.php',
        'Zuora\InvoiceFile' => __DIR__ .'/InvoiceFile.php',
        'Zuora\Refund' => __DIR__ .'/Refund.php',
        'Zuora\RefundInvoicePayment' => __DIR__ .'/RefundInvoicePayment.php',
        'Zuora\RefundTransactionLog' => __DIR__ .'/RefundTransactionLog.php',
        'Zuora\InvoiceItem' => __DIR__ .'/InvoiceItem.php',
        'Zuora\InvoicePayment' => __DIR__ .'/InvoicePayment.php',
        'Zuora\Payment' => __DIR__ .'/Payment.php',
        'Zuora\PaymentTransactionLog' => __DIR__ .'/PaymentTransactionLog.php',
        'Zuora\PaymentMethod' => __DIR__ .'/PaymentMethod.php',
        'Zuora\PaymentMethodTransactionLog' => __DIR__ .'/PaymentMethodTransactionLog.php',
        'Zuora\PaymentMethodSnapshot' => __DIR__ .'/PaymentMethodSnapshot.php',
        'Zuora\UnitOfMeasure' => __DIR__ .'/UnitOfMeasure.php',
        'Zuora\Product' => __DIR__ .'/Product.php',
        'Zuora\Feature' => __DIR__ .'/Feature.php',
        'Zuora\ProductFeature' => __DIR__ .'/ProductFeature.php',
        'Zuora\ProductRatePlan' => __DIR__ .'/ProductRatePlan.php',
        'Zuora\ProductRatePlanCharge' => __DIR__ .'/ProductRatePlanCharge.php',
        'Zuora\ProductRatePlanChargeTier' => __DIR__ .'/ProductRatePlanChargeTier.php',
        'Zuora\GatewayOption' => __DIR__ .'/GatewayOption.php',
        'Zuora\RatePlan' => __DIR__ .'/RatePlan.php',
        'Zuora\SubscriptionProductFeature' => __DIR__ .'/SubscriptionProductFeature.php',
        'Zuora\RatePlanCharge' => __DIR__ .'/RatePlanCharge.php',
        'Zuora\RatePlanChargeTier' => __DIR__ .'/RatePlanChargeTier.php',
        'Zuora\Subscription' => __DIR__ .'/Subscription.php',
        'Zuora\TaxationItem' => __DIR__ .'/TaxationItem.php',
        'Zuora\Usage' => __DIR__ .'/Usage.php',
        'Zuora\Import' => __DIR__ .'/Import.php',
        'Zuora\CreditBalanceAdjustment' => __DIR__ .'/CreditBalanceAdjustment.php',
        'Zuora\Export' => __DIR__ .'/Export.php',
        'Zuora\CommunicationProfile' => __DIR__ .'/CommunicationProfile.php',
        'Zuora\InvoiceSplit' => __DIR__ .'/InvoiceSplit.php',
        'Zuora\InvoiceSplitItem' => __DIR__ .'/InvoiceSplitItem.php',
        'Zuora\BillingPreviewRun' => __DIR__ .'/BillingPreviewRun.php',
        'Zuora\ChargeMetrics' => __DIR__ .'/ChargeMetrics.php',
        'Zuora\ChargeMetricsRun' => __DIR__ .'/ChargeMetricsRun.php',
        'Zuora\LoginResult' => __DIR__ .'/LoginResult.php',
        'Zuora\SubscribeRequest' => __DIR__ .'/SubscribeRequest.php',
        'Zuora\SubscribeOptions' => __DIR__ .'/SubscribeOptions.php',
        'Zuora\SubscribeInvoiceProcessingOptions' => __DIR__ .'/SubscribeInvoiceProcessingOptions.php',
        'Zuora\SubscriptionData' => __DIR__ .'/SubscriptionData.php',
        'Zuora\RatePlanData' => __DIR__ .'/RatePlanData.php',
        'Zuora\SubscriptionProductFeatureList' => __DIR__ .'/SubscriptionProductFeatureList.php',
        'Zuora\RatePlanChargeData' => __DIR__ .'/RatePlanChargeData.php',
        'Zuora\ProductRatePlanChargeTierData' => __DIR__ .'/ProductRatePlanChargeTierData.php',
        'Zuora\InvoicePaymentData' => __DIR__ .'/InvoicePaymentData.php',
        'Zuora\RefundInvoicePaymentData' => __DIR__ .'/RefundInvoicePaymentData.php',
        'Zuora\GatewayOptionData' => __DIR__ .'/GatewayOptionData.php',
        'Zuora\InvoiceData' => __DIR__ .'/InvoiceData.php',
        'Zuora\InvoiceResult' => __DIR__ .'/InvoiceResult.php',
        'Zuora\ChargeMetricsData' => __DIR__ .'/ChargeMetricsData.php',
        'Zuora\NewChargeMetrics' => __DIR__ .'/NewChargeMetrics.php',
        'Zuora\PreviewOptions' => __DIR__ .'/PreviewOptions.php',
        'Zuora\SubscribeResult' => __DIR__ .'/SubscribeResult.php',
        'Zuora\SaveResult' => __DIR__ .'/SaveResult.php',
        'Zuora\DeleteResult' => __DIR__ .'/DeleteResult.php',
        'Zuora\ExecuteResult' => __DIR__ .'/ExecuteResult.php',
        'Zuora\QueryResult' => __DIR__ .'/QueryResult.php',
        'Zuora\Error' => __DIR__ .'/Error.php',
        'Zuora\ChargeMetricsError' => __DIR__ .'/ChargeMetricsError.php',
        'Zuora\ErrorCode' => __DIR__ .'/ErrorCode.php',
        'Zuora\login' => __DIR__ .'/login.php',
        'Zuora\loginResponse' => __DIR__ .'/loginResponse.php',
        'Zuora\calculateRequest' => __DIR__ .'/calculateRequest.php',
        'Zuora\calculateChargeMetrics' => __DIR__ .'/calculateChargeMetrics.php',
        'Zuora\calculateResult' => __DIR__ .'/calculateResult.php',
        'Zuora\calculateResponse' => __DIR__ .'/calculateResponse.php',
        'Zuora\subscribe' => __DIR__ .'/subscribe.php',
        'Zuora\subscribeResponse' => __DIR__ .'/subscribeResponse.php',
        'Zuora\create' => __DIR__ .'/create.php',
        'Zuora\createResponse' => __DIR__ .'/createResponse.php',
        'Zuora\generate' => __DIR__ .'/generate.php',
        'Zuora\generateResponse' => __DIR__ .'/generateResponse.php',
        'Zuora\update' => __DIR__ .'/update.php',
        'Zuora\updateResponse' => __DIR__ .'/updateResponse.php',
        'Zuora\delete' => __DIR__ .'/delete.php',
        'Zuora\deleteResponse' => __DIR__ .'/deleteResponse.php',
        'Zuora\execute' => __DIR__ .'/execute.php',
        'Zuora\executeResponse' => __DIR__ .'/executeResponse.php',
        'Zuora\query' => __DIR__ .'/query.php',
        'Zuora\queryResponse' => __DIR__ .'/queryResponse.php',
        'Zuora\queryMore' => __DIR__ .'/queryMore.php',
        'Zuora\queryMoreResponse' => __DIR__ .'/queryMoreResponse.php',
        'Zuora\SessionHeader' => __DIR__ .'/SessionHeader.php',
        'Zuora\QueryOptions' => __DIR__ .'/QueryOptions.php',
        'Zuora\getUserInfoResponse' => __DIR__ .'/getUserInfoResponse.php',
        'Zuora\getUserInfo' => __DIR__ .'/getUserInfo.php',
        'Zuora\DummyHeader' => __DIR__ .'/DummyHeader.php',
        'Zuora\CallOptions' => __DIR__ .'/CallOptions.php',
        'Zuora\InvoiceProcessingOptions' => __DIR__ .'/InvoiceProcessingOptions.php',
        'Zuora\AmendOptions' => __DIR__ .'/AmendOptions.php',
        'Zuora\AmendRequest' => __DIR__ .'/AmendRequest.php',
        'Zuora\amend' => __DIR__ .'/amend.php',
        'Zuora\AmendResult' => __DIR__ .'/AmendResult.php',
        'Zuora\amendResponse' => __DIR__ .'/amendResponse.php',
        'Zuora\ElectronicPaymentOptions' => __DIR__ .'/ElectronicPaymentOptions.php',
        'Zuora\ExternalPaymentOptions' => __DIR__ .'/ExternalPaymentOptions.php',
        'Zuora\BillingPreviewRequest' => __DIR__ .'/BillingPreviewRequest.php',
        'Zuora\billingPreview' => __DIR__ .'/billingPreview.php',
        'Zuora\BillingPreviewResult' => __DIR__ .'/BillingPreviewResult.php',
        'Zuora\billingPreviewResponse' => __DIR__ .'/billingPreviewResponse.php',
        'Zuora\ApiFault' => __DIR__ .'/ApiFault.php',
        'Zuora\LoginFault' => __DIR__ .'/LoginFault.php',
        'Zuora\InvalidTypeFault' => __DIR__ .'/InvalidTypeFault.php',
        'Zuora\InvalidValueFault' => __DIR__ .'/InvalidValueFault.php',
        'Zuora\MalformedQueryFault' => __DIR__ .'/MalformedQueryFault.php',
        'Zuora\InvalidQueryLocatorFault' => __DIR__ .'/InvalidQueryLocatorFault.php',
        'Zuora\UnexpectedErrorFault' => __DIR__ .'/UnexpectedErrorFault.php'
    );
    if (!empty($classes[$class])) {
        include $classes[$class];
    };
}

spl_autoload_register('autoload_96d2f8e914b6a5f32a1e79c3b6aeba4d');

// Do nothing. The rest is just leftovers from the code generation.
{
}
