<?php

namespace Zuora;

class ErrorCode
{
    const __default = 'API_DISABLED';
    const API_DISABLED = 'API_DISABLED';
    const CANNOT_DELETE = 'CANNOT_DELETE';
    const CREDIT_CARD_PROCESSING_FAILURE = 'CREDIT_CARD_PROCESSING_FAILURE';
    const DUPLICATE_VALUE = 'DUPLICATE_VALUE';
    const INVALID_FIELD = 'INVALID_FIELD';
    const INVALID_LOGIN = 'INVALID_LOGIN';
    const INVALID_SESSION = 'INVALID_SESSION';
    const INVALID_TYPE = 'INVALID_TYPE';
    const INVALID_ID = 'INVALID_ID';
    const INVALID_VALUE = 'INVALID_VALUE';
    const INVALID_VERSION = 'INVALID_VERSION';
    const LOCK_COMPETITION = 'LOCK_COMPETITION';
    const MALFORMED_QUERY = 'MALFORMED_QUERY';
    const MAX_RECORDS_EXCEEDED = 'MAX_RECORDS_EXCEEDED';
    const MISSING_REQUIRED_VALUE = 'MISSING_REQUIRED_VALUE';
    const NO_PERMISSION = 'NO_PERMISSION';
    const SERVER_UNAVAILABLE = 'SERVER_UNAVAILABLE';
    const UNKNOWN_ERROR = 'UNKNOWN_ERROR';
    const TRANSACTION_FAILED = 'TRANSACTION_FAILED';
    const INVALID_TEMPLATE = 'INVALID_TEMPLATE';
    const ACCOUNTING_PERIOD_CLOSED = 'ACCOUNTING_PERIOD_CLOSED';
    const BATCH_FAIL_ERROR = 'BATCH_FAIL_ERROR';
    const PDF_QUERY_ERROR = 'PDF_QUERY_ERROR';
    const REQUEST_EXCEEDED_LIMIT = 'REQUEST_EXCEEDED_LIMIT';
    const REQUEST_EXCEEDED_RATE = 'REQUEST_EXCEEDED_RATE';
    const REQUEST_REJECTED = 'REQUEST_REJECTED';
    const TEMPORARY_ERROR = 'TEMPORARY_ERROR';
    const TRANSACTION_TERMINATED = 'TRANSACTION_TERMINATED';
    const TRANSACTION_TIMEOUT = 'TRANSACTION_TIMEOUT';


}
